import React from 'react'
import { Container } from 'react-bootstrap'

const TermsandConditionsScreen = () =>
{
    return (
        <Container>
            <h1>Terms and Conditions</h1>
            <p>The use of IshMishDreams.com website is subject to the following terms & conditions: <br /><br />
1.       The content available on the website is for your general information and use only. Terms we, us are used for IshMishDreams.com while you are for buyer, a person surfing website or someone outsider of our knowledge, client and person or group taking our services. <br /><br />
2.       We reserve the right, in our sole discretion, to make changes or modifications to these Terms and Conditions at any time and for any reason. You have to check for updates time to time. <br /><br />
3.       The information provided on the Site is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation or which would subject us to any registration requirement within such jurisdiction or country. <br /><br />
4.       Accordingly, those persons who choose to access the Site from other locations do so on their own initiative and are solely responsible for compliance with local laws, if and to the extent local laws are applicable. <br /><br />
5.       Unless otherwise indicated, the Site is our proprietary property and source code, databases, functionality, software, website designs, audio, video, text, photographs, and graphics on the Site (collectively, the “Content”) and the trademarks, service marks, and logos contained therein (the “Marks”) are owned or controlled by us or licensed to us, and are protected by copyright and trademark laws and various other intellectual property rights and unfair competition laws of the Republic of India, foreign jurisdictions, and international conventions. <br /><br />
6.       You shall not upload to, distribute, or otherwise publish through this Site any Content, information, or other material that violates or infringes the copyrights, patents, trademarks, service marks, trade secrets, or other proprietary rights of any person and IshMishDreams.com. <br /><br />
7.       Threatening, defamatory act, obscene material, indecent, pornographic content or any criminal activity by using our name is strictly prohibited. Trying to use any bugs, viruses, worms, trap doors, Trojan horses or other harmful code or properties are strictly prohibited. <br /><br />
8.       You have a limited permission to access and use the website only for the purpose of shopping for personal items sold on the Site and not for any commercial use or use on behalf of any third party. Any breach of this Agreement will result immediately in the revocation of the permission given to you without informing to you and your account will be terminated or blocked. <br /><br />
9.       The Content and the Marks are provided on the Site “AS IS” for your information only. Except as expressly provided in these Terms and Conditions, no part of the Site and no Content or Marks may be copied, reproduced, aggregated, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted, distributed, sold, licensed, or otherwise exploited for any commercial purpose whatsoever, without our express prior written permission<br /><br />
10.    You may not sell, distribute, display, lease, transfer, translate, modify, reverse-engineering, disassemble, decompile or otherwise exploit this Site or any portion of it. You cannot use information available on this website for any unfair, personal, commercial use. <br /><br />
11.    We reserve the rights to cancel order (in some conditions like items unavailability and unforeseen/natural scenarios), terminate accounts if customer violates applicable law or is harmful to IshMishDreams.com interests. <br /><br />
12.    Violations of system or network security, security of the site may result in civil or criminal liability. Logging onto a server or an account which you are not authorized to access, attempting to download our photograph, attempting to probe, scan or test the vulnerability of a system or network, attempting to interfere with service to any other user, host or network, including, without limitation, via means of submitting a virus to the Site, overloading, flooding, spamming and such other offences are strictly prohibited and are punishable as per Indian laws. <br /><br />
13.    You are not permitted to send objectionable, illegal, unauthorised/spam email on the name of IshMishDreams.com/from site account. You are not allowed to misuse our website email accounts by any means. <br /><br />
14.    Forging any TCP/IP packet header or any part of the header information in any email or newsgroup posting is prohibited /not permitted. <br /><br />
15.    You agree not to use any device, software or routine to interfere or attempt to interfere with the proper working of this Site or any activity being conducted on this Site. <br /><br />
16.    In case of any breach of terms or violation of the Agreement by us, you will notify us in Private first by email or phone about the possible breach and agree grant at least 100 days to investigate and resolve this. If we will not be able to resolve this, you will send a legal notice clearly mentioning breach with proof and will grant 3 months to rectify the breach or violation. <br /><br />
17.    You may be required to register with the Site. You agree to keep your password confidential and will be responsible for all use/ activities of your account that occur under your Display Name and Password. You agree that if You provide any information that is untrue, inaccurate, not current or incomplete or We have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with this Terms of Use, we shall have the right to indefinitely suspend or terminate or block access of Your membership/account on the Website and refuse to provide You with access to the Website. We reserve the right to remove a username you select if we determine, in our sole discretion, that such username is inappropriate, obscene, or otherwise objectionable. <br /><br />
18.    We collect some information from you(cookies) and use it to make online shopping a hassle-free process for you. <br /><br />
19.    Any attempt to damage the image of IshMishDreams.com is strictly not permitted, you may not create a link to this website from another website or document without our prior express written consent. Unauthorized linking to the website by any means is not permitted and will be treated as offence. The Site may not be used in connection with any commercial endeavours except those that are specifically endorsed or approved by us. <br /><br />
20.    Your use of any information or materials on this website is entirely at your own risk, for which we shall not be liable. It shall be your own responsibility to ensure that any products or information available through this website meet your specific requirements. <br /><br />
21.    We do not provide warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials found or offered on this website for any particular purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law. <br /><br />
22.    There may be information on the Site that contains typographical errors, inaccuracies, or omissions that may relate to the Site, including descriptions, pricing, availability, and various other information. We reserve the right to correct any errors, inaccuracies, or omissions and to change or update the information on the Site at any time, without prior notice. <br /><br />
23.    We may provide you areas on the Site to leave reviews or ratings. When posting a review, you must comply with the following criteria: <br /><br />
a.     you should have first-hand experience with the item being reviewed; <br />
b.     your reviews should not contain offensive profanity, or abusive, racist, offensive, or hate language; <br />
c.      your reviews should not contain discriminatory references based on religion, race, gender, national origin, age, marital status, sexual orientation, or disability; <br />
d.     your reviews should not contain references to illegal activity; <br />
e.     you should not be affiliated with competitors if posting negative reviews; <br />
f.      you should not make any conclusions as to the legality of conduct; <br />
g.     you may not post any false or misleading statements; <br />
h.     you may not organize a campaign encouraging others to post reviews, whether positive or negative. <br /><br />
24.    We may accept, reject, or remove reviews in our sole discretion. We have absolutely no obligation to screen reviews or to delete reviews, even if anyone considers reviews objectionable or inaccurate. Reviews are not endorsed by us, and do not necessarily represent our opinions or the views of any of our affiliates or partners. <br /><br />
25.    We do not assume liability for any review or for any claims, liabilities, or losses resulting from any review. By posting a review, you hereby grant to us a perpetual, non-exclusive, worldwide, royalty-free, fully-paid, assignable, and sublicensable right and license to reproduce, modify, translate, transmit by any means, display, perform, and/or distribute all content relating to reviews. <br /><br />
26.    You acknowledge and agree that any questions, comments, suggestions, ideas, feedback, or other information regarding the Site (“Submissions”) provided by you to us are non-confidential and shall become our sole property. We shall own exclusive rights, including all intellectual property rights, and shall be entitled to the unrestricted use and dissemination of these Submissions for any lawful purpose, commercial or otherwise, without acknowledgment or compensation to you. <br /><br />
27.    You hereby waive all moral rights to any such Submissions, and you hereby warrant that any such Submissions are original with you or that you have the right to submit such Submissions. You agree there shall be no recourse against us for any alleged or actual infringement or misappropriation of any proprietary right in your Submissions. <br /><br />
28.    By accessing IshMishDreams.com you have read, understood, and agree to be bound by all of these Terms and Conditions. If you do not agree with all of these Terms and Conditions, then you are expressly prohibited from using the site and you must discontinue use immediately. <br /><br />

            </p>
        </Container>
    )
}

export default TermsandConditionsScreen
